### ISSUE TITLE
Two geometry loading same material src only one can show up

### ISSUE THREAD

**Issue by LiCong1992** [mayognaise/aframe-video-shader#2]
##I try to load the same source video to two different geometry, but only one can show the video. Of course I tried load different videos and it worked and I can load the same video twice to solve this problem but that's a waste of bandwidth and sync is also tricky. Here's the demo code:

```
  <a-entity id="video" geometry="primitive:box;width:4;height:2.15;depth:2;" rotation="30 30 0" position="0 2 0" material="shader:video;src:#bbb;"></a-entity>
  <a-entity id="video1" geometry="primitive:box;width:4;height:2.15;depth:2;" rotation="30 30 0" position="0 6 0" material="shader:video;src:#bbb;"></a-entity>
```

So is there a way to fix it?

**Comment by mayognaise** [comment]
hi @LiCong1992, if it is under iOS9, it only plays one video. what's the environment?

**Comment by LiCong1992** [comment]
Hi @mayognaise  and thanks for your reply. 
I've tested with iOS8.1.2 and iOS9.3.2 and both of them failed to play. In fact I've tried to combined your work with oscarmarinmiro's aframe-stereo-component(https://github.com/oscarmarinmiro/aframe-stereo-component) to create a stereo player(which displays side by side videos) that can be used with iOS 9 and iOS8.  I can try to draw one side of the 3D video by changing the parameters of drawImage(), but I fail to render another side of the video because the problem I posted. Anything helpful would be appreciated!

**Comment by mayognaise** [comment]
hi @LiCong1992, i assume it's because the OS cannot play more than one video.
under iOS9 includes iOS9.x. so that's why it doesn't work.
for the nearer future, iOS10 does support inline video playback so you can just use aframe's core shader. 😄
